services_msgs/InitRobotState init_robot_state
services_msgs/DesiredState[] desired_states
services_msgs/GainsValues[] gains
float64[] model_params
float64[] initial_xi
float64[] time_vec
float64 t_init
float64 t_final
float64 dt
string integrator
---
float64[] final_xi
float64[] trajX
float64[] trajY
float64[] trajZ
float64[] trajVX
float64[] trajVY
float64[] trajVZ
float64[] trajQw
float64[] trajQx
float64[] trajQy
float64[] trajQz
float64[] trajWx
float64[] trajWy
float64[] trajWz
float64[] u1
float64[] u2
float64[] u3
float64[] u4
float64 executionTime